sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t thajib/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thajib/docker-react npm run test
  

