version: '3'
services:
  react-app:
    user: root
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /frontend_app/node_modules
      - .:/frontend_app

  react-test:
    user: root
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /frontend_app/node_modules
      - .:/frontend_app
    command: ["npm", "run", "test"]
    