FROM node:alpine

USER root

WORKDIR '/frontend_app'

COPY package.json .

USER root

RUN npm install

COPY . .

ENV NODE_OPTIONS=--openssl-legacy-provider

CMD ["npm", "run", "start"]
